Description: EC2 webserver provisioned in account Default VPC

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0db188056a6ff81ae # Amazon Linux AMI in Ireland
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: '8'
            Encrypted: 'true'
            DeleteOnTermination: 'true'
      SecurityGroupIds:
        - !GetAtt 'WebSecurityGroup.GroupId'
      SubnetId: subnet-044010fc8031c578d
      Tags:
        - Key: Name
          Value: samb-de-webserver
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y && yum install -y httpd # Install apache web server
          systemctl start httpd && systemctl enable httpd # Start webserver
          echo "Hello World" > /var/www/html/index.html # Create web content
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP ingress on port 80
      VpcId: vpc-09736265f09bd9a1b
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
